server {
    listen 80;
    server_name _;

    location / {
        root /app/ui;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /docs/ {
        alias /app/docs/;
        autoindex on;
    }

    location /api/ {
        proxy_pass http://risk-api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
